// Messages Consts
const UPDATE_MESSAGES = "UPDATE_MESSAGES";
const NEW_MESSAGE = "NEW_MESSAGE";
const POST_MESSAGE = "POST_MESSAGE";
const LIKE_MESSAGE = "LIKE_MESSAGE";

//Products Consts
const PRODUCTS_AGREGATE = "PRODUCTS_AGREGATE";


module.exports = {
//const Messages Exports
UPDATE_MESSAGES,
NEW_MESSAGE,
POST_MESSAGE,
LIKE_MESSAGE,
//const Products Exports
PRODUCTS_AGREGATE,
}
